framework:
    workflows:
        regular_package:
            type: state_machine
            audit_trail:
                enabled: true

        ### Разобрать что за type и что за property
        # marking_store:
        #   type: 'method'
        #   property: 'state'
        ### Тут либо supports: array
        ### Либо support_strategy
            support_strategy: App\Infrastructure\Workflow\SupportStrategies\PackageSupportStrategyService
            places:
                - import
                - measuring
                - sorting
                - store
                - pallet
                - shipping
                - delay
                - done
            transitions:
                to_measure:
                    from: import
                    to: measuring
                to_sorting:
                    from: measuring
                    to: sorting
                to_storing:
                    from: measuring
                    to: store
                to_pallet:
                    from: sorting
                    to: pallet
                to_shipping:
                    from: pallet
                    to: shipping
                to_delay:
                    from: shipping
                    to: delay
                to_done:
                    from: shipping
                    to: done
                to_delay_return:
                    from: delay
                    to: import
        delay_package:
            type: state_machine
            audit_trail:
                enabled: true
            support_strategy: App\Infrastructure\Workflow\SupportStrategies\PackageSupportStrategyService
            places:
                - import
                - storing
                - restoring
            transitions:
                to_store:
                    from: import
                    to: storing
                to_restoring:
                    from: storing
                    to: restoring
                to_import:
                    from: restoring
                    to: import
#Идея перегрузки workflow для складов - сделать декоратор для registry
# и массив с workflow подменять взависимости от текущего выбраного склада
# подменяя оригинальные на те что с расширением
#        delay_package.sha:
#            type: state_machine
#            audit_trail:
#                enabled: true
#            support_strategy: App\Infrastructure\Workflow\SupportStrategies\PackageSupportStrategyService
#            places:
#                - import
#                - storing
#                - restoring
#            transitions:
#                to_store:
#                    from: import
#                    to: storing
#                to_restoring:
#                    from: storing
#                    to: restoring
#                to_import:
#                    from: restoring
#                    to: import
