framework:
    workflows:
        package:
            type: state_machine
            audit_trail:
                enabled: true

        ### Разобрать что за type и что за property
        # marking_store:
        #   type: 'method'
        #   property: 'state'
        ### Тут либо supports: array
        ### Либо support_strategy

            support_strategy: App\Workflow\PackageSupportStrategyService
            places:
                - import
                - measuring
                - sorting
                - store
                - pallet
                - shipping
                - delay
                - done
            transitions:
                measure:
                    from: [import]
                    to: measuring
                sorting:
                    from: measuring
                    to: sorting
                storing:
                    from: measuring
                    to: store
                pallet:
                    from: sorting
                    to: pallet
                shipping:
                    from: pallet
                    to: shipping
                delay:
                    from: shipping
                    to: delay
                done:
                    from: shipping
                    to: done
                delay_return:
                    from: delay
                    to: import

        delay_storing:
            type: state_machine
            audit_trail:
                enabled: true
            support_strategy: App\Workflow\PackageSupportStrategyService
            places:
                - import
                - place
                - replace
            transitions:
                store:
                    from: import
                    to: place



