framework:
    workflows:
        package_regular:
            type: state_machine
            audit_trail:
                enabled: true
            #TODO: Уточнить что к чему \Symfony\Config\Framework\Workflows\WorkflowsConfig\MarkingStoreConfig
            marking_store:
                type: 'method'
                property: 'currentPlace'
            support_strategy: App\Infrastructure\Workflow\SupportStrategies\PlaceableSupportStrategyService
            places:
                import:
#                    metadata:
#                        bg_color: grey
#                        description: 'meta description'
                measuring: ~
                sorting: ~
                store: ~
                pallet: ~
                shipping: ~
                delay: ~
                done: ~
            transitions:
                to_measure:
                    from: import
                    to: measuring
#                    metadata:
#                        label: 'to_measure_metadata'
#                        color: 'blue'
#                        arrow_color: 'red'
                to_sorting:
                    from: measuring
                    to: sorting
                to_storing:
                    from: measuring
                    to: store
                to_pallet:
                    from: sorting
                    to: pallet
                to_shipping:
                    from: pallet
                    to: shipping
                to_delay:
                    from: shipping
                    to: delay
                to_done:
                    from: shipping
                    to: done
                to_delay_return:
                    from: delay
                    to: import
        package_delay:
            type: state_machine
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            support_strategy: App\Infrastructure\Workflow\SupportStrategies\PlaceableSupportStrategyService
            places:
               import: ~
               storing: ~
               restoring: ~
            transitions:
                to_store:
                    from: import
                    to: storing
                to_restoring:
                    from: storing
                    to: restoring
                to_import:
                    from: restoring
                    to: import
#Идея перегрузки workflow для складов - сделать декоратор для registry
# и массив с workflow подменять взависимости от текущего выбраного склада
# подменяя оригинальные на те что с расширением
#        delay_package.sha:
#            type: state_machine
#            audit_trail:
#                enabled: true
#            support_strategy: App\Infrastructure\Workflow\SupportStrategies\PackageSupportStrategyService
#            places:
#                - import
#                - storing
#                - restoring
#            transitions:
#                to_store:
#                    from: import
#                    to: storing
#                to_restoring:
#                    from: storing
#                    to: restoring
#                to_import:
#                    from: restoring
#                    to: import
        pallet_regular:
            type: state_machine
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            support_strategy: App\Infrastructure\Workflow\SupportStrategies\PlaceableSupportStrategyService
            places:
                new: ~
                band: ~
                disband: ~
                sent: ~
                shipping: ~
            transitions:
                banding:
                    from: [new, disband]
                    to: band
                disbanding:
                    from: band
                    to: disband
                to_sent:
                    from: band
                    to: sent
                to_ship:
                    from: band
                    to: shipping