version: "3.7"
services:
    node:
        image: node:16
        working_dir: /var/www/application
        user: node
        volumes:
            - ..:/var/www/application
        networks:
            - warehousenetwork

networks:
    warehousenetwork:
        external:
            name: warehousenetwork
